---
name: Sample Workflow
on:
  push:
    branches:
    - '*'
    tags:
    - '*'
  workflow_dispatch:
    inputs:
      foo:
        description: 'foo string'
        required: false
        type: string
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "building ${{ github.event.inputs.foo }}"
