---
name: Sample Workflow
on:
  push:
    branches:
    - '*'
    tags:
    - '*'
  workflow_dispatch:
    inputs:
      foo:
        description: 'infamous foo'
        required: false
        type: string
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "building"
