---
name: MyLib NuGet
# run-name: ${{ github.actor }} is building
on:
  push:
    branches:
    - '*'
    tags:
    - '*'
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "building"
