---
name: Build
# run-name: ${{ github.actor }} is building
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-2022
    steps:
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
