---
name: Sample Workflow
on:
  push:
    branches:
    - '*'
    tags:
    - '*'
  workflow_dispatch:
    inputs:
      foo:
        description: 'foo string'
        required: false
        type: string
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repository (Latest)
      uses: actions/checkout@v2
      if: github.event.inputs.foo == ''
    - name: Clone Repository (${{ github.event.inputs.foo }})
      uses: actions/checkout@v2
      if: github.event.inputs.foo != ''
      with:
        ref: ${{ github.event.inputs.foo }}
