---
name: Build
# run-name: ${{ github.actor }} is building
on: [push]
jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Setup .NET SDK 6.0.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
